
services:
  app:
    image: whitedeepdive/mobile-environment-app:latest
    container_name: mobile-environment-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    restart: always
    depends_on:
      db:
          condition: service_healthy
    ports:
      - 8080:8080


  db:
    image: mysql:8.0
    restart: always
    container_name: mobile-environment-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
    mysql_data: