## 공통 설정 파일
spring:
  jackson:
    default-property-inclusion: non_null

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      max-file-size: 20MB # 단일 파일의 최대 크기

  jpa:
    defer-datasource-initialization: true



  jwt:
    secret: ${JWT_SECRET}

