name: Code Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 파일 가져오기
        uses: actions/checkout@v4

      - name: jdk 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: gradle 파일 실행 권한 설정
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean build
